#!/bin/bash

pgrep -x sxhkd > /dev/null || sxhkd &
dunst &
polybar &
feh --bg-fill ~/pictures/maxresdefault_4xup.jpg &

bspc monitor DisplayPort-0 -d 4 5 6
bspc monitor DisplayPort-2 -d 1 2 3

bspc config border_width 2
bspc config window_gap 15
bspc config split_ratio 0

bspc config focused_border_color "#f5c2e7"
bspc config active_border_color "#45475a"
bspc config normal_border_color "#45475a"
bspc config presel_feedback_color "#45475a"

bspc config focus_follows_pointer true
bspc config pointer_modifier mod4

bspc config automatic_scheme
